# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created: Mon Apr 28 21:04:29 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 509)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ComboBoxDestino = QtGui.QComboBox(self.centralwidget)
        self.ComboBoxDestino.setGeometry(QtCore.QRect(210, 360, 221, 20))
        self.ComboBoxDestino.setObjectName(_fromUtf8("ComboBoxDestino"))
        self.ComboBoxOrigen = QtGui.QComboBox(self.centralwidget)
        self.ComboBoxOrigen.setGeometry(QtCore.QRect(210, 60, 221, 20))
        self.ComboBoxOrigen.setObjectName(_fromUtf8("ComboBoxOrigen"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 360, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 170, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 140, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.CheckBoxAutor = QtGui.QCheckBox(self.centralwidget)
        self.CheckBoxAutor.setGeometry(QtCore.QRect(270, 260, 70, 17))
        self.CheckBoxAutor.setObjectName(_fromUtf8("CheckBoxAutor"))
        self.CheckBoxTitulo = QtGui.QCheckBox(self.centralwidget)
        self.CheckBoxTitulo.setGeometry(QtCore.QRect(270, 290, 70, 17))
        self.CheckBoxTitulo.setObjectName(_fromUtf8("CheckBoxTitulo"))
        self.CheckBoxEditor = QtGui.QCheckBox(self.centralwidget)
        self.CheckBoxEditor.setGeometry(QtCore.QRect(360, 260, 70, 17))
        self.CheckBoxEditor.setObjectName(_fromUtf8("CheckBoxEditor"))
        self.CheckBoxPublicador = QtGui.QCheckBox(self.centralwidget)
        self.CheckBoxPublicador.setGeometry(QtCore.QRect(360, 290, 70, 17))
        self.CheckBoxPublicador.setObjectName(_fromUtf8("CheckBoxPublicador"))
        self.RadioButtonDebate = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonDebate.setGeometry(QtCore.QRect(60, 260, 82, 17))
        self.RadioButtonDebate.setObjectName(_fromUtf8("RadioButtonDebate"))
        self.RadioButtonArticulo = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonArticulo.setGeometry(QtCore.QRect(150, 260, 82, 17))
        self.RadioButtonArticulo.setObjectName(_fromUtf8("RadioButtonArticulo"))
        self.RadioButtonLibro = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonLibro.setGeometry(QtCore.QRect(60, 290, 82, 17))
        self.RadioButtonLibro.setObjectName(_fromUtf8("RadioButtonLibro"))
        self.RadioButtonColeccion = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonColeccion.setGeometry(QtCore.QRect(150, 290, 82, 17))
        self.RadioButtonColeccion.setObjectName(_fromUtf8("RadioButtonColeccion"))
        self.RadioButtonTesis = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonTesis.setGeometry(QtCore.QRect(60, 320, 82, 17))
        self.RadioButtonTesis.setObjectName(_fromUtf8("RadioButtonTesis"))
        self.RadioButtonOtros = QtGui.QRadioButton(self.centralwidget)
        self.RadioButtonOtros.setGeometry(QtCore.QRect(150, 320, 82, 17))
        self.RadioButtonOtros.setObjectName(_fromUtf8("RadioButtonOtros"))
        self.ButtonCancelar = QtGui.QPushButton(self.centralwidget)
        self.ButtonCancelar.setGeometry(QtCore.QRect(350, 440, 75, 23))
        self.ButtonCancelar.setObjectName(_fromUtf8("ButtonCancelar"))
        self.ButtonProcesar = QtGui.QPushButton(self.centralwidget)
        self.ButtonProcesar.setGeometry(QtCore.QRect(260, 440, 75, 23))
        self.ButtonProcesar.setObjectName(_fromUtf8("ButtonProcesar"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 230, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 230, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ButtonDescargar = QtGui.QPushButton(self.centralwidget)
        self.ButtonDescargar.setGeometry(QtCore.QRect(340, 90, 91, 23))
        self.ButtonDescargar.setObjectName(_fromUtf8("ButtonDescargar"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(50, 90, 281, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.TerminoBusqueda = QtGui.QTextEdit(self.centralwidget)
        self.TerminoBusqueda.setGeometry(QtCore.QRect(50, 190, 381, 31))
        self.TerminoBusqueda.setObjectName(_fromUtf8("TerminoBusqueda"))
        self.NombreFichero = QtGui.QTextEdit(self.centralwidget)
        self.NombreFichero.setGeometry(QtCore.QRect(210, 390, 221, 31))
        self.NombreFichero.setObjectName(_fromUtf8("NombreFichero"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 400, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.progressBar_2 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_2.setEnabled(True)
        self.progressBar_2.setGeometry(QtCore.QRect(47, 440, 201, 16))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setGeometry(QtCore.QRect(460, 10, 491, 451))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("https://campusvirtual.unican.es/Identificacion/IdentificacionFrw.aspx")))
        self.webView.setObjectName(_fromUtf8("webView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def resize_window(self, MainWindow, ancho, alto):
        MainWindow.resize(ancho, alto)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Origen de Datos", None))
        self.label_2.setText(_translate("MainWindow", "Destino de Procesado", None))
        self.label_3.setText(_translate("MainWindow", "Termino de busqueda", None))
        self.label_4.setText(_translate("MainWindow", "Filtro de Procesado", None))
        self.label_5.setText(_translate("MainWindow", "Plataformas de Trabajo", None))
        self.CheckBoxAutor.setText(_translate("MainWindow", "Autor", None))
        self.CheckBoxTitulo.setText(_translate("MainWindow", "Titulo", None))
        self.CheckBoxEditor.setText(_translate("MainWindow", "Editor", None))
        self.CheckBoxPublicador.setText(_translate("MainWindow", "Publicador", None))
        self.RadioButtonDebate.setText(_translate("MainWindow", "Debate", None))
        self.RadioButtonArticulo.setText(_translate("MainWindow", "Articulo", None))
        self.RadioButtonLibro.setText(_translate("MainWindow", "Libro", None))
        self.RadioButtonColeccion.setText(_translate("MainWindow", "Coleccion", None))
        self.RadioButtonTesis.setText(_translate("MainWindow", "Tesis", None))
        self.RadioButtonOtros.setText(_translate("MainWindow", "Otros", None))
        self.ButtonCancelar.setText(_translate("MainWindow", "Cancelar", None))
        self.ButtonProcesar.setText(_translate("MainWindow", "Procesar", None))
        self.label_6.setText(_translate("MainWindow", "Parametros a buscar", None))
        self.label_7.setText(_translate("MainWindow", "Tipo de documento", None))
        self.ButtonDescargar.setText(_translate("MainWindow", "Descargar Datos", None))
        self.label_8.setText(_translate("MainWindow", "Nombre Fichero", None))

from PyQt4 import QtWebKit
